sudo: false

language: go

services:
  - docker

env:
  - GO111MODULE=on

go:
  - 1.12.x
  - 1.14.x
  - 1.15.x
  - 1.16.x

git:
  depth: 1

install: true

notifications:
  email: false

script:
  - make check
  - make cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
