sudo: false

language: go

services:
  - docker

env:
  - GO111MODULE=on

go:
  - 1.12.x

git:
  depth: 1

install: true

notifications:
  email: false

script:
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  - make check
  - make cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
